# Generated by Django 4.1.3 on 2022-12-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founded_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
